apiVersion: v1
kind: Pod
metadata:
  name: readdata
spec:
  containers:
  - name: alpine
    image: alpine:latest
    command: ['sleep', 'infinity']
    volumeMounts:
    - name: mypvc
      mountPath: /data
      # mountPath: /source # The file path in the container
      # readOnly: true     # Access mode to the data mount from pv
      # subPath: test        # The file path in pv, should be <repo-name>
  volumes:
  - name: mypvc
    persistentVolumeClaim:
      claimName: test-pvc
